"""add interpreters

Revision ID: 04df27ab54e3
Revises: 2155b574822b
Create Date: 2025-12-13 12:01:58.649595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04df27ab54e3'
down_revision = '2155b574822b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interpreters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('access_tier', sa.String(length=16), nullable=False),
    sa.Column('unlock_rule', mysql.JSON(), nullable=True),
    sa.Column('core_voice', sa.Text(), nullable=False),
    sa.Column('interpretive_lens', sa.Text(), nullable=False),
    sa.Column('emotional_stance', sa.Text(), nullable=False),
    sa.Column('prompt_extra', sa.Text(), nullable=True),
    sa.Column('card_blurb', sa.String(length=255), nullable=False),
    sa.Column('card_bullets', mysql.JSON(), nullable=False),
    sa.Column('tone_examples', mysql.JSON(), nullable=False),
    sa.Column('icon_key', sa.String(length=64), nullable=False),
    sa.Column('icon_file', sa.String(length=128), nullable=True),
    sa.Column('icon_tile_file', sa.String(length=128), nullable=True),
    sa.Column('icon_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_interpreters_slug')
    )
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ux_subscription_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.create_index('ux_subscription_token', ['payment_provider', 'provider_transaction_id'], unique=True)

    op.drop_table('interpreters')
    # ### end Alembic commands ###
