"""Add user avatar table

Revision ID: 052190dfae80
Revises: ac93c9fc15ee
Create Date: 2025-05-23 13:58:05.376551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052190dfae80'
down_revision = 'ac93c9fc15ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendingusers', schema=None) as batch_op:
        batch_op.drop_index('idx_pendingusers_email_lower')
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_filename', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_filename')

    with op.batch_alter_table('pendingusers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('idx_pendingusers_email_lower', [sa.literal_column('lower(email::text)')], unique=True)

    # ### end Alembic commands ###
