"""update free tokens

Revision ID: 2155b574822b
Revises: 5739a8333707
Create Date: 2025-12-09 11:55:44.404413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2155b574822b'
down_revision = '5739a8333707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credits', schema=None) as batch_op:
        batch_op.drop_index('uq_user_credits_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credits', schema=None) as batch_op:
        batch_op.create_index('uq_user_credits_user_id', ['user_id'], unique=True)

    # ### end Alembic commands ###
