"""Add user language

Revision ID: 275a5eb55d30
Revises: 392e1374fd5f
Create Date: 2025-05-31 08:28:37.651808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275a5eb55d30'
down_revision = '392e1374fd5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendingusers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('pendingusers', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
