"""add tone

Revision ID: 392e1374fd5f
Revises: 052190dfae80
Create Date: 2025-05-29 14:32:30.820115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392e1374fd5f'
down_revision = '052190dfae80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.drop_column('tone')

    # ### end Alembic commands ###
