"""Add apple_user_id to User model

Revision ID: 5739a8333707
Revises: e21df4415bc9
Create Date: 2025-12-05 17:39:19.352954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5739a8333707'
down_revision = 'e21df4415bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apple_user_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_apple_user_id'), ['apple_user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_apple_user_id'))
        batch_op.drop_column('apple_user_id')

    # ### end Alembic commands ###
