"""New: rich feature cards (title + description, optional metadata)

Revision ID: 5890423a5d72
Revises: bab3068b82b2
Create Date: 2026-01-06 10:21:38.949013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5890423a5d72'
down_revision = 'bab3068b82b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_cards', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_column('feature_cards')

    # ### end Alembic commands ###
