"""Remove image_url from Dream

Revision ID: 616629c50a45
Revises: 275a5eb55d30
Create Date: 2025-06-05 11:09:01.899714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616629c50a45'
down_revision = '275a5eb55d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
