"""add aminated icon to interpreters

Revision ID: 966dba1c7c71
Revises: 5890423a5d72
Create Date: 2026-03-19 20:28:53.454933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966dba1c7c71'
down_revision = '5890423a5d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interpreters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animated_icon_file', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interpreters', schema=None) as batch_op:
        batch_op.drop_column('animated_icon_file')

    # ### end Alembic commands ###
