"""add user_credit table

Revision ID: 9beceb7de71c
Revises: 1e79bb1bd27f
Create Date: 2025-11-08 00:12:42.707641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9beceb7de71c'
down_revision = '1e79bb1bd27f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_credits',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text_remaining_week', sa.Integer(), nullable=False),
    sa.Column('image_remaining_lifetime', sa.Integer(), nullable=False),
    sa.Column('week_anchor_utc', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_credits')
    # ### end Alembic commands ###
