"""rename text_remaining_week to free_credits, image_remaining_lifetime to purchased_credits; add credit_packs table

Revision ID: a7fed3616e08
Revises: 966dba1c7c71
Create Date: 2026-03-22 17:17:54.709174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7fed3616e08'
down_revision = '966dba1c7c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('product_id', sa.String(length=128), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_credits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_credits', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('purchased_credits', sa.Integer(), nullable=False))
        batch_op.drop_column('text_remaining_week')
        batch_op.drop_column('image_remaining_lifetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_remaining_lifetime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('text_remaining_week', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('purchased_credits')
        batch_op.drop_column('free_credits')

    op.drop_table('credit_packs')
    # ### end Alembic commands ###
