"""Add discussion table

Revision ID: bab3068b82b2
Revises: ff33952ff337
Create Date: 2025-12-23 15:08:22.841654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab3068b82b2'
down_revision = 'ff33952ff337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discuss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dream_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dream_id'], ['dream.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discuss', schema=None) as batch_op:
        batch_op.create_index('ix_discuss_dream_created', ['dream_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_discuss_dream_id'), ['dream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discuss_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discuss', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discuss_user_id'))
        batch_op.drop_index(batch_op.f('ix_discuss_dream_id'))
        batch_op.drop_index('ix_discuss_dream_created')

    op.drop_table('discuss')
    # ### end Alembic commands ###
