"""updates from AZAD

Revision ID: e21df4415bc9
Revises: ff8c6e3e74ba
Create Date: 2025-12-03 21:34:53.731704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21df4415bc9'
down_revision = 'ff8c6e3e74ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_confirm_tokens', schema=None) as batch_op:
        batch_op.drop_index('uq_email_confirm_tokens_token_hash')
        batch_op.create_index(batch_op.f('ix_email_confirm_tokens_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_confirm_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_confirm_tokens_token_hash'))
        batch_op.create_index('uq_email_confirm_tokens_token_hash', ['token_hash'], unique=True)

    # ### end Alembic commands ###
