"""Add alias and remove icon_tile_file from interpreters table

Revision ID: ff33952ff337
Revises: 04df27ab54e3
Create Date: 2025-12-17 10:17:22.532216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff33952ff337'
down_revision = '04df27ab54e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interpreters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', sa.String(length=120), nullable=False))
        batch_op.drop_column('icon_tile_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interpreters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_tile_file', mysql.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('alias')

    # ### end Alembic commands ###
